[workspace]
authors = ["Arthur Lin <alin62@wisc.edu>"]
channels = ["conda-forge"]
name = "htcondor"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[system-requirements]
cuda = "12"
